theme: jekyll-theme-architect

title: [jstl-api]
description: [Servlet Implementation]

# sidebar links url
links:
  source: https://github.com/javaee/jstl-api
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

